---
title: "Code chunks"
author: "ottavia"
format: 
  html: 
   toc: true
   toc-location: left
   number-sections: true
   code-tools: 
     source: true
     toggle: false
     caption: Show the code for this document
   grid:
    sidebar-width: 200px
    body-width: 900px
    margin-width: 400px
    gutter-width: 1.5rem
   theme: 
    light: minty
    dark: superhero 
self-contained: true
lang: en
bibliography: biblio.bib
reference-location: margin
citation-location: margin
execute: 
  echo: false
editor_options: 
  chunk_output_type: console
---

```{r}
#| echo: true
#| error: true
mean(y)
```



@lst-default presents the default settings of the code chunks

```{r}
#| lst-label: lst-default
#| lst-cap: Default settings
head(cars)
```



```{r}
#| echo: false
#| lst-label: lst-echoF
#| lst-cap: Echo FALSE
head(cars)
```


```{r}
#| echo: true
#| eval: false
#| lst-label: lst-echoF
#| lst-cap: Echo TRUE, EVAL FALSE
head(cars)
```

@fig-normal presents a normal distribution. 

```{r}
#| label: fig-normal
#| fig-cap: A normal distribution
x = seq(-3,3, length.out = 10000)
dx = dnorm(x)
plot(x, dx, type = "l", cex = 2, lwd = 3)
```

@fig-normalProperties illustrates properties. @fig-normalProperties-1, @fig-normalProperties-2, and @fig-normalProperties-3

```{r}
#| layout-ncol: 3
#| label: fig-normalProperties
#| fig-cap: Normal distribution
#| fig-subcap: 
#|   - "Density"
#|   - "Cumulative"
#|   - "Quantile"
plot(x, dx, type = "l", cex = 2, lwd = 3)
plot(x, pnorm(x), type = "l", cex = 2, lwd = 3)
plot( pnorm(x),qnorm( pnorm(x)), type = "l", cex = 2, lwd = 3)

```

@tbl-tab

```{r}
#| tbl-cap: This is my firsat table
#| label: tbl-tab
library(knitr)
kable(head(cars))
```

```{r}
#| fig-column: margin
#| tbl-cap: The table 
#| fig-cap: The plot
kable(head(cars))
plot(cars$speed, cars$dist)
```


